TYPE=VIEW
query=select `recycl`.`EMPLOYE`.`motdepasse` AS `motdepasse`,`recycl`.`EMPLOYE`.`blocked` AS `blocked`,`recycl`.`EMPLOYE`.`login` AS `login`,`recycl`.`EMPLOYE`.`date_mdp` AS `date_mdp` from `recycl`.`EMPLOYE`
md5=02261d48c99cd532cd799edd9b021754
updatable=1
algorithm=0
definer_user=RecyclDbUser
definer_host=%
suid=2
with_check_option=0
timestamp=2020-05-11 14:06:23
create-version=1
source=Select motdepasse, blocked, login, date_mdp\nFrom EMPLOYE
client_cs_name=utf8mb4
connection_cl_name=utf8mb4_general_ci
view_body_utf8=select `recycl`.`EMPLOYE`.`motdepasse` AS `motdepasse`,`recycl`.`EMPLOYE`.`blocked` AS `blocked`,`recycl`.`EMPLOYE`.`login` AS `login`,`recycl`.`EMPLOYE`.`date_mdp` AS `date_mdp` from `recycl`.`EMPLOYE`
