TYPE=VIEW
query=select `recycl`.`EMPLOYE`.`motdepasse` AS `motdepasse`,`recycl`.`EMPLOYE`.`blocked` AS `blocked`,`recycl`.`EMPLOYE`.`login` AS `login`,`recycl`.`EMPLOYE`.`date_mdp` AS `date_mdp` from `recycl`.`EMPLOYE`
md5=02261d48c99cd532cd799edd9b021754
updatable=1
algorithm=0
definer_user=root
definer_host=%
suid=1
with_check_option=0
timestamp=2020-05-27 13:32:07
create-version=1
source=select `EMPLOYE`.`motdepasse` AS `motdepasse`,`EMPLOYE`.`blocked` AS `blocked`,`EMPLOYE`.`login` AS `login`,`EMPLOYE`.`date_mdp` AS `date_mdp` from `EMPLOYE`
client_cs_name=utf8
connection_cl_name=utf8_general_ci
view_body_utf8=select `recycl`.`EMPLOYE`.`motdepasse` AS `motdepasse`,`recycl`.`EMPLOYE`.`blocked` AS `blocked`,`recycl`.`EMPLOYE`.`login` AS `login`,`recycl`.`EMPLOYE`.`date_mdp` AS `date_mdp` from `recycl`.`EMPLOYE`
