version: '3'
services:
  db_container_recycl:
    container_name: db_container_recycl
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'recycl'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'RecyclDbUser'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'RecyclPassword34'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'rootingpassword'
    volumes:
      - /home/sql/recycl/sql_vol:/var/lib/mysql
      - ./Ressources-MSPR-TPRE604/Ressources-MSPR-TPRE604/:/ressource
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - "8082:3306"
    expose:
      # Opens port 3306 on the container
      - "3306"
    networks:
      - backend

  app:
    build: ./
    ports:
      - "8585:8080"
    depends_on:
      - db_container_recycl
    networks:
      - backend
    restart: always

networks:
  backend:
    driver: bridge


